config/routes.rb
Phonebook::Application.routes.draw do
  devise_for :users
  resources :accounts
  resources :phones do
    resources :phonelists
  end

  root to: 'phones#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
        user ||= User.new # guest user (not logged in)
        if user.role == "Administrator"
          can :manage, :all
        else
          alias_action :read, :update, :destroy, :to => :rud
          can :rud, Phone, :user_id => user.id
          can :create, Phone

          alias_action :read, :update, :destroy, :to => :rud
          can :rud, Phonelist, :phone => { :user_id => user.id }
          can :create, Phonelist
        end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  	belongs_to :user
	has_many	:phonelists, dependent: :destroy
	# validates :nomer, presence: true, uniqueness: { scope: :nomer, message: "should not duplicates"}
	# validates :name, presence: true, uniqueness: { scope: :name, message: "should not duplicates"}
  validates :nomer, presence: true
  validates :name, presence: true
end

app/models/phonelist.rb
class Phonelist < ActiveRecord::Base
  	belongs_to :phone, :foreign_key => "phone_id", :class_name => "Phone"
  	validates :namelist, presence: true
    validates :nomerlist, presence: true
  	# validates :nomerlist, presence: true, :uniqueness => {:scope => [:nomerlist, :phone_id], message: "number already exists"}

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many  :phones, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController


  def index
    @accounts = User.all
  end

  def edit
    @account = User.find(params[:id])
    authorize! :edit, @account
  end

  def update
    authorize! :update, @account
    @account = User.find(params[:id])
    if @account.update(params[:account].permit(:role))
      redirect_to accounts_url
    else
      render 'edit'
    end
  end

  def show
   @account = User.find(params[:id])
 end

 def destroy
  @account = User.find(params[:id])
  authorize! :destroy, @account
  @account.destroy

  redirect_to accounts_url
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  rescue_from CanCan::Error do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url, :alert => "You are not authorized to access that page."
  end

  rescue_from ActiveRecord::RecordNotFound do |exception|
    redirect_to root_url, :alert => "Sorry, record not found."
  end

end

app/controllers/phonelists_controller.rb
class PhonelistsController < ApplicationController
  load_and_authorize_resource

	def create
		@phone = Phone.find(params[:phone_id])
		@phonelist = @phone.phonelists.create(phonelist_params)
		redirect_to phone_path(@phone)
	end
	def destroy
		@phone = Phone.find(params[:phone_id])
		@phonelist = @phone.phonelists.find(params[:id])
		@phonelist.destroy
		redirect_to phone_path(@phone)
	end
	def edit
        @phone = Phone.find(params[:phone_id])
        @phonelist = @phone.phonelists.find(params[:id])
  end
  def update
   	@phone = Phone.find(params[:phone_id])
	  @phonelist = @phone.phonelists.find(params[:id])

	  if @phonelist.update(params[:phonelist].permit(:namelist, :nomerlist))
			redirect_to @phone
		else
			render 'edit'
		end
  end


  private
    def phonelist_params
      params.require(:phonelist).permit(:namelist, :nomerlist)
   end

end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
   load_and_authorize_resource

    def index
      # if current_user.role == "Administrator"
        @phones = Phone.all.order("name ASC")
      # else
      #   @phones = Phone.all.order("name ASC").where(user_id: current_user.id)
      # end
    end

    def new
       @phone = Phone.new
    end

    def create
       @phone = Phone.new(phone_params)
       # if current_user.role == "Administrator"
        @phones = Phone.all.order("name ASC")
       # else
       #  @phones = Phone.all.order("name ASC").where(user_id: current_user.id)
       # end

       respond_to do |format|
        if @phone.save
          format.html { redirect_to @phone, notice: "Phone created" }
          format.js
        else
          format.html {render 'new'}
          format.js
        end
       end
    end

   def show
       @phone = Phone.find(params[:id])
   end

   def destroy
       @phone = Phone.find(params[:id])
       @phone.destroy

       redirect_to @phone
   end

   def edit
       @phone = Phone.find(params[:id])
   end

   def update
       @phone = Phone.find(params[:id])
       # if current_user.role == "Administrator"
        @phones = Phone.all.order("name ASC")
       # else
       #  @phones = Phone.all.order("name ASC").where(user_id: current_user.id)
       # end
       if @phone.update(params[:phone].permit(:name, :nomer))
           render 'index'
       else
           render 'edit'
       end
   end

   private
    def phone_params
      params.require(:phone).permit(:name, :nomer, :user_id)
   end
 end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_helper.rb
module PhoneHelper
end

app/helpers/phonelists_helper.rb
module PhonelistsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/edit.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>Edit User Administration</strong></div>
  <div class="panel-body">

      <%= form_for :account, url: account_path(@account.id),method: :patch  do |f| %>

      <div class="row">
        <div class="col-xs-6 col-sm-4">
          <%= f.label :user_email %>
          <%=f.text_field :email, :class => 'form-control input-sm', :disabled => true %>
        </div>

        <div class=  "col-xs-6 col-sm-4">
            <%= f.label :role %> <br \>
            <%= f.radio_button :role, "User", checked: @account.role == "User", class: 'multiple_classes' %> <%= f.label :label_role, "User"%>
            &nbsp;
            <%= f.radio_button :role, "Administrator", checked: @account.role == "Administrator", class: 'multiple_classes' %> <%= f.label :label_role, "Administrator"%>
        </div>

          <div class="col-xs-6 col-sm-4">
          <br \>
          <button class="btn btn-primary btn-sm">save administration</button>
          </div>
      </div>

      <% end %>

      <p></p>
      <br \>
      <ul class="pager">
        <li class="previous"><%= link_to '<< back', accounts_path %></li>
      </ul>

  </div>
</div>

app/views/accounts/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>User Administration</strong></div>
  <div class="panel-body">
<table width="750" align="center" class="table table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <th>User e-mail</th>
      <th>last_sign_in_at</th>
      <th>Role</th>
      <th colspan='3'>Actions</th>
    </tr>
  </thead>
  <tbody>

    <% @accounts.each_with_index do |account, idx| %>
    <tr>
     <td><%= idx+1 %>.</td>
     <td><%= account.email %></td>
     <td><%= account.last_sign_in_at %></td>
     <td><%= account.role %></td>
     <td><%= link_to 'edit', edit_account_path(account), :class => 'btn btn-default btn-xs'%></td>
     <td>
      <%= link_to 'delete', account_path(account),
     method: :delete, data: {confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %>
     </td>
   </tr>
   <% end %>
 </tbody>
</table>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>phonebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<div class="navbar navbar-default" role="navigation">
  <a class="navbar-brand"><strong>PHONEBOOK</strong></a>
  <div id="user_nav" class="navbar-text pull-right">
    <% if user_signed_in? %>
        Signed in as <%= current_user.email %> |
        <%= link_to "Home", phones_path %> |
        <%= link_to "Account", accounts_path %> |
        <%= link_to "SignOut", destroy_user_session_path, :method => :delete %>
    <% else %>
        <%= link_to "SignUp", new_user_registration_path %> or <%= link_to "SignIn", new_user_session_path %>
    <% end %>
  </div>
</div>
<body>
<div class="container" style="max-width:650px;">
  <%= yield %>
</div>
</body>
</html>

app/views/phonelists/edit.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>Edit Phonelist</strong></div>
  <div class="panel-body">


      <%= form_for :phonelist, url: phone_phonelist_path(@phone.id, @phonelist.id),method: :patch  do |f| %>
      <div class="row">
      	<div class="col-xs-6 col-sm-4">
          <%= f.label :contact_name %>
          <%=f.text_field :namelist, :class => "form-control input-sm" %>
      	</div>

      	<div class="col-xs-6 col-sm-4">
          <%= f.label :phone_number %>
          <%=f.text_field :nomerlist, :class => "form-control input-sm"  %>
        	</div>

        	<div class="col-xs-6 col-sm-4">
          <br \>
          <button class="btn btn-primary btn-sm">save phonelist</button>
      	</div>
      </div>

      <% end %>

      <p></p>
      <br \>
      <ul class="pager">
        <li class="previous"><%= link_to '<< back', phone_path(@phone.id) %></li>
      </ul>

  </div>
</div>

app/views/phones/_contacts.html.erb
<table width="750" align="center" class="table table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <th>Contact name</th>
      <th>Phone number</th>
      <th colspan='3'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% i=0 %>
    <% @phones.each do |phone| %>
    <% if can? :rud, phone %>
    <tr>
     <td><%= i += 1 %>.</td>
     <td><%= link_to phone.name, phone_path(phone) %></td>
     <td><%= phone.nomer %></td>
     <td><%= link_to 'edit', edit_phone_path(phone), :class => 'btn btn-default btn-xs'%></td>
     <td>
      <%= link_to 'delete', phone_path(phone),
     method: :delete, data: {confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %>
     </td>
   </tr>
   <% end %>
   <% end %>
 </tbody>
</table>

app/views/phones/create.js.erb
$("#kontak_list").html("<%= escape_javascript(render("contacts")) %>");

app/views/phones/edit.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>Edit Phonebook</strong></div>
  <div class="panel-body">

      <%= form_for :phone, url: phone_path(@phone.id),method: :patch  do |f| %>

      <div class="row">
      	<div class="col-xs-6 col-sm-4">
          <%= f.label :contact_name %>
          <%=f.text_field :name, :class => 'form-control input-sm' %>
      	</div>

      	<div class="col-xs-6 col-sm-4">
          <%= f.label :phone_number %>
          <%=f.text_field :nomer, :class => 'form-control input-sm' %>
        	</div>

        	<div class="col-xs-6 col-sm-4">
        	<br \>
        	<button class="btn btn-primary btn-sm">save phone</button>
        	</div>
      </div>

      <% end %>

      <p></p>
      <br \>
      <ul class="pager">
        <li class="previous"><%= link_to '<< back', phones_path %></li>
      </ul>

  </div>
</div>

app/views/phones/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>Add Phonebook</strong></div>
  <div class="panel-body">
    <%=flash[:notice]%><%=flash[:alert]%><%=flash[:message]%>
    <%= form_tag phones_path, :remote => "true" do %>
    <br \>
    <div class="row">
        <div class="col-xs-6 col-sm-4">
            <%= label_tag(:name_label, "Contact name") %>
            <%= text_field_tag "phone[name]", nil, class: 'form-control input-sm', placeholder: 'Enter contact name...' %>
            <%= hidden_field_tag 'phone[user_id]', current_user.id %>
        </div>
        <div class="col-xs-6 col-sm-4">
            <%= label_tag(:nomer_label, "Phone number") %>
            <%= text_field_tag "phone[nomer]", nil, class: 'form-control input-sm', placeholder: 'Enter phone number...' %>
        </div>
        <br \>
        <button class="btn btn-primary btn-sm">add phone</button>
    </div>
    <% end %>

    <br \>


    <div id="kontak_list"><%= render 'contacts' %></div>
</div>
</div>

app/views/phones/show.html.erb
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><strong>Phonelist Number</strong></div>
    <div class="panel-body">
         <table>
        	<tr>
        		<td><strong>Contact Name </strong></td>
        		<td><strong>&nbsp;&nbsp; : &nbsp;&nbsp;</strong></td>
        		<td><%= @phone.name %></td>
        	</tr>
        	<tr>
        		<td><strong>Phone Number </strong></td>
        		<td><strong>&nbsp;&nbsp; : &nbsp;&nbsp;</strong></td>
        		<td><%= @phone.nomer %></td>
        	</tr>
        </table>
         <p></p>
         <br \>
        <table align="center" class="table table-striped">
        <thead>
          <tr>
            <th>No.</th>
            <th>Contact name</th>
            <th>Phone number</th>
            <th colspan='3'>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @phone.phonelists.each_with_index do |phonelist, idx| %>
          <tr>
          	<td><%= idx+1 %>.</td>
          	<td><%= phonelist.namelist %></td>
          	<td><%= phonelist.nomerlist %></td>
          	<td><%= link_to 'edit', edit_phone_phonelist_path(phonelist.phone, phonelist), :class => 'btn btn-default btn-xs' %></td>
          	<td><%= link_to 'delete', [phonelist.phone, phonelist],
        				method: :delete,
        				data: { confirm: 'Are you sure' }, :class => 'btn btn-danger btn-xs' %></td>
          </tr>
          <% end %>

          </tbody>
        </table>

        <%= form_for([@phone, @phone.phonelists.build]) do |f| %>
        <div class="row">
        	<div class="col-xs-6 col-sm-4">
        	<%= f.label :contact_name_list %><br />
        	<%= f.text_field :namelist, :class => "form-control  input-sm", placeholder: 'Enter contact name list...' %>
        	</div>

        	<div class="col-xs-6 col-sm-4">
        	<%= f.label :phone_number_list %><br />
        	<%= f.text_field :nomerlist, :class => "form-control  input-sm", placeholder: 'Enter phone number list...' %>
        	</div>

        	<div class="col-xs-6 col-sm-4">
        	<br \>
            <button class="btn btn-primary btn-sm">add phonelist</button>
          	</div>
        </div>
        <% end %>

        <p></p>
        <br \>

        <ul class="pager">
          <li class="previous"><%= link_to '<< back', phones_path %></li>
        </ul>


      </div>
  </div>